# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Repos/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/recording_inst_0/ip/recording_inst_0_axis_data_fifo_0_0/recording_inst_0_axis_data_fifo_0_0.xci
# IP: The module: 'recording_inst_0_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/recording_inst_0/ip/recording_inst_0_axis_data_fifo_0_0/recording_inst_0_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'recording_inst_0_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Repos/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/recording_inst_0/ip/recording_inst_0_axis_data_fifo_0_0/recording_inst_0_axis_data_fifo_0_0.xci
# IP: The module: 'recording_inst_0_axis_data_fifo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/recording_inst_0/ip/recording_inst_0_axis_data_fifo_0_0/recording_inst_0_axis_data_fifo_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'recording_inst_0_axis_data_fifo_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
