# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/xpm_cdc_1bit/xpm_cdc_1bit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xpm_cdc_1bit || ORIG_REF_NAME==xpm_cdc_1bit} -quiet] -quiet

# IP: bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xpm_cdc_1bit_xpm_cdc_0_0 || ORIG_REF_NAME==xpm_cdc_1bit_xpm_cdc_0_0} -quiet] -quiet

# Block Designs: bd/rhd_rhs_tb/rhd_rhs_tb.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rhd_rhs_tb || ORIG_REF_NAME==rhd_rhs_tb} -quiet] -quiet

# IP: bd/rhd_rhs_tb/ip/rhd_rhs_tb_axi_vip_0_0/rhd_rhs_tb_axi_vip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rhd_rhs_tb_axi_vip_0_0 || ORIG_REF_NAME==rhd_rhs_tb_axi_vip_0_0} -quiet] -quiet

# IP: bd/rhd_rhs_tb/ip/rhd_rhs_tb_axi_vip_0_1/rhd_rhs_tb_axi_vip_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rhd_rhs_tb_axi_vip_0_1 || ORIG_REF_NAME==rhd_rhs_tb_axi_vip_0_1} -quiet] -quiet

# IP: bd/rhd_rhs_tb/ip/rhd_rhs_tb_seeg_0_0/rhd_rhs_tb_seeg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rhd_rhs_tb_seeg_0_0 || ORIG_REF_NAME==rhd_rhs_tb_seeg_0_0} -quiet] -quiet

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# Block Designs: bd/xpm_cdc_1bit/xpm_cdc_1bit.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xpm_cdc_1bit || ORIG_REF_NAME==xpm_cdc_1bit} -quiet] -quiet

# IP: bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xpm_cdc_1bit_xpm_cdc_0_0 || ORIG_REF_NAME==xpm_cdc_1bit_xpm_cdc_0_0} -quiet] -quiet

# XDC: c:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.gen/sources_1/bd/xpm_cdc_1bit/xpm_cdc_1bit_ooc.xdc

# XDC: c:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.gen/sources_1/bd/xpm_cdc_1bit/xpm_cdc_1bit_ooc.xdc

# XDC: c:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.gen/sources_1/bd/rhd_rhs_tb/rhd_rhs_tb_ooc.xdc
