# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.srcs/sources_1/bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3.xci
# IP: The module: 'main_proc_sys_reset_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.srcs/sources_1/bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3.xci
# IP: The module: 'main_proc_sys_reset_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_proc_sys_reset_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
