# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Repos/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.srcs/sources_1/bd/main/ip/main_smartconnect_0_1/main_smartconnect_0_1.xci
# IP: The module: 'main_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Repos/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/bd_b752.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Repos/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Repos/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.srcs/sources_1/bd/main/ip/main_smartconnect_0_1/main_smartconnect_0_1.xci
# IP: The module: 'main_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Repos/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/bd_b752.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Repos/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
