# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/xpm_cdc_1bit/xpm_cdc_1bit.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xpm_cdc_1bit || ORIG_REF_NAME==xpm_cdc_1bit} -quiet] -quiet

# IP: bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xpm_cdc_1bit_xpm_cdc_0_0 || ORIG_REF_NAME==xpm_cdc_1bit_xpm_cdc_0_0} -quiet] -quiet

# XDC: c:/Users/anhha/Desktop/UG3_HeadWornUnitV2_FPGA/rhs/rhs.gen/sources_1/bd/xpm_cdc_1bit/xpm_cdc_1bit_ooc.xdc
