# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.srcs/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0.xci
# IP: The module: 'xpm_cdc_1bit_xpm_cdc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.gen/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/synth/xpm_cdc_1bit_xpm_cdc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xpm_cdc_1bit_xpm_cdc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.gen/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xpm_cdc_1bit_xpm_cdc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.srcs/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0.xci
# IP: The module: 'xpm_cdc_1bit_xpm_cdc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.gen/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/synth/xpm_cdc_1bit_xpm_cdc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xpm_cdc_1bit_xpm_cdc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.gen/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xpm_cdc_1bit_xpm_cdc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
