# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.srcs/sources_1/bd/rhd_rhs_tb/ip/rhd_rhs_tb_axi_vip_0_1/rhd_rhs_tb_axi_vip_0_1.xci
# IP: The module: 'rhd_rhs_tb_axi_vip_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.gen/sources_1/bd/rhd_rhs_tb/ip/rhd_rhs_tb_axi_vip_0_1/rhd_rhs_tb_axi_vip_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rhd_rhs_tb_axi_vip_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.srcs/sources_1/bd/rhd_rhs_tb/ip/rhd_rhs_tb_axi_vip_0_1/rhd_rhs_tb_axi_vip_0_1.xci
# IP: The module: 'rhd_rhs_tb_axi_vip_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/UG3-HeadWornUnit-V2-Firmware/seeg_tb/seeg_tb.gen/sources_1/bd/rhd_rhs_tb/ip/rhd_rhs_tb_axi_vip_0_1/rhd_rhs_tb_axi_vip_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rhd_rhs_tb_axi_vip_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
