# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/main/main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main || ORIG_REF_NAME==main} -quiet] -quiet

# IP: bd/main/ip/main_zynq_ultra_ps_e_0_0/main_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==main_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/main/ip/main_smartconnect_0_0/main_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_smartconnect_0_0 || ORIG_REF_NAME==main_smartconnect_0_0} -quiet] -quiet

# IP: bd/main/ip/main_proc_sys_reset_0_0/main_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_proc_sys_reset_0_0 || ORIG_REF_NAME==main_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/main/ip/main_smartconnect_0_1/main_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_smartconnect_0_1 || ORIG_REF_NAME==main_smartconnect_0_1} -quiet] -quiet

# IP: bd/main/ip/main_clk_wiz_0_0/main_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_clk_wiz_0_0 || ORIG_REF_NAME==main_clk_wiz_0_0} -quiet] -quiet

# IP: bd/main/ip/main_proc_sys_reset_0_1/main_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_proc_sys_reset_0_1 || ORIG_REF_NAME==main_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/main/ip/main_proc_sys_reset_0_2/main_proc_sys_reset_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_proc_sys_reset_0_2 || ORIG_REF_NAME==main_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/main/ip/main_smartconnect_0_2/main_smartconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_smartconnect_0_2 || ORIG_REF_NAME==main_smartconnect_0_2} -quiet] -quiet

# IP: bd/main/ip/main_axi_dma_0_0/main_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_axi_dma_0_0 || ORIG_REF_NAME==main_axi_dma_0_0} -quiet] -quiet

# IP: bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_proc_sys_reset_0_3 || ORIG_REF_NAME==main_proc_sys_reset_0_3} -quiet] -quiet

# IP: bd/main/ip/main_clk_wiz_1_0/main_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_clk_wiz_1_0 || ORIG_REF_NAME==main_clk_wiz_1_0} -quiet] -quiet

# XDC: c:/Repos/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/main_ooc.xdc
