# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.runs/synth_1/main_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.cache/wt [current_project]
set_property parent.project_path /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:k26c:part0:1.4 [current_project]
set_property ip_output_repo /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/hdl/main_wrapper.v
add_files /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.srcs/sources_1/bd/main/main.bd
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_zynq_ultra_ps_e_0_0/main_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_zynq_ultra_ps_e_0_0/main_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_1/bd_7793_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_1/bd_7793_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_2/bd_7793_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_2/bd_7793_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_3/bd_7793_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_3/bd_7793_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_4/bd_7793_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_5/bd_7793_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_6/bd_7793_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_7/bd_7793_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_8/bd_7793_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_9/bd_7793_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_10/bd_7793_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_11/bd_7793_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_12/bd_7793_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_13/bd_7793_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_14/bd_7793_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_15/bd_7793_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_16/bd_7793_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_17/bd_7793_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_18/bd_7793_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_22/bd_7793_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_23/bd_7793_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_24/bd_7793_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_25/bd_7793_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_26/bd_7793_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_27/bd_7793_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_28/bd_7793_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_29/bd_7793_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_30/bd_7793_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_31/bd_7793_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_32/bd_7793_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_33/bd_7793_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_35/bd_7793_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_36/bd_7793_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_37/bd_7793_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_38/bd_7793_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_39/bd_7793_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_40/bd_7793_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_42/bd_7793_m02s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_43/bd_7793_m02arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_44/bd_7793_m02rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_45/bd_7793_m02awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_46/bd_7793_m02wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/bd_0/ip/ip_47/bd_7793_m02bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_0/main_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_0/main_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_0/main_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_1/bd_b752_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_1/bd_b752_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_2/bd_b752_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_2/bd_b752_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_3/bd_b752_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_3/bd_b752_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_4/bd_b752_psr_aclk2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_4/bd_b752_psr_aclk2_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_5/bd_b752_arinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_6/bd_b752_rinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_7/bd_b752_awinsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_8/bd_b752_winsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_9/bd_b752_binsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_10/bd_b752_aroutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_11/bd_b752_routsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_12/bd_b752_awoutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_13/bd_b752_woutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_14/bd_b752_boutsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_15/bd_b752_arni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_16/bd_b752_rni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_17/bd_b752_awni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_18/bd_b752_wni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_19/bd_b752_bni_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_23/bd_b752_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_24/bd_b752_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_25/bd_b752_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_26/bd_b752_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_27/bd_b752_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_28/bd_b752_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_29/bd_b752_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_30/bd_b752_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_31/bd_b752_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_32/bd_b752_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_33/bd_b752_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_34/bd_b752_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_36/bd_b752_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_37/bd_b752_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_38/bd_b752_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_39/bd_b752_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_40/bd_b752_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/bd_0/ip/ip_41/bd_b752_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_1/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_clk_wiz_0_0/main_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_clk_wiz_0_0/main_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_clk_wiz_0_0/main_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_1/main_proc_sys_reset_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_1/main_proc_sys_reset_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_1/main_proc_sys_reset_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_2/main_proc_sys_reset_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_2/main_proc_sys_reset_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_2/main_proc_sys_reset_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_1/bd_b612_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_1/bd_b612_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_2/bd_b612_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_3/bd_b612_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_4/bd_b612_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_5/bd_b612_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_6/bd_b612_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_10/bd_b612_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_11/bd_b612_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_12/bd_b612_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_13/bd_b612_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_14/bd_b612_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_15/bd_b612_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_19/bd_b612_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_20/bd_b612_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_21/bd_b612_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_22/bd_b612_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_23/bd_b612_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_24/bd_b612_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_25/bd_b612_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_26/bd_b612_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_27/bd_b612_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/bd_0/ip/ip_28/bd_b612_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_smartconnect_0_2/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_axi_dma_0_0/main_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_axi_dma_0_0/main_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_axi_dma_0_0/main_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_proc_sys_reset_0_3/main_proc_sys_reset_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_clk_wiz_1_0/main_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_clk_wiz_1_0/main_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/ip/main_clk_wiz_1_0/main_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/main_ooc.xdc]

add_files /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/recording_inst_0/recording_inst_0.bd
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/recording_inst_0/ip/recording_inst_0_axis_data_fifo_0_0/recording_inst_0_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/recording_inst_0/ip/recording_inst_0_rhd_axi_0_0/recording_inst_0_rhd_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/recording_inst_0/recording_inst_0_ooc.xdc]

add_files /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/stimulation_inst_0/stimulation_inst_0.bd
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/stimulation_inst_0/ip/stimulation_inst_0_axis_data_fifo_0_0/stimulation_inst_0_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/stimulation_inst_0/ip/stimulation_inst_0_rhs_axi_0_0/stimulation_inst_0_rhs_axi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.gen/sources_1/bd/main/bd/stimulation_inst_0/stimulation_inst_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.srcs/constrs_1/new/constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/ug3linux/UG3-HeadWornUnit-V2-Firmware/seeg/seeg.srcs/utils_1/imports/synth_1/rhd_axi.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top main_wrapper -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_wrapper_utilization_synth.rpt -pb main_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
