set_property SRC_FILE_INFO {cfile:c:/Repos/UG3-HeadWornUnit-V2-Firmware/rhd/rhd.gen/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0_in_context.xdc rfile:../../../../../rhd.gen/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0_in_context.xdc id:1 order:EARLY scoped_inst:inst/rhd_S00_AXI/rhd/fifo_inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Repos/UG3-HeadWornUnit-V2-Firmware/rhd/rhd.gen/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0_in_context.xdc rfile:../../../../../rhd.gen/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0_in_context.xdc id:2 order:EARLY scoped_inst:inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_1/xpm_cdc_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Repos/UG3-HeadWornUnit-V2-Firmware/rhd/rhd.gen/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0_in_context.xdc rfile:../../../../../rhd.gen/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0_in_context.xdc id:3 order:EARLY scoped_inst:inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_2/xpm_cdc_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Repos/UG3-HeadWornUnit-V2-Firmware/rhd/rhd.gen/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0_in_context.xdc rfile:../../../../../rhd.gen/sources_1/bd/xpm_cdc_1bit/ip/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0/xpm_cdc_1bit_xpm_cdc_0_0_in_context.xdc id:4 order:EARLY scoped_inst:inst/rhd_S00_AXI/rhd/xpm_cdc_5bit_inst_3/xpm_cdc_0} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Repos/UG3-HeadWornUnit-V2-Firmware/rhd/rhd.gen/sources_1/bd/rhd_axi_tb/ip/rhd_axi_tb_rhd_axi_0_0/rhd_axi_tb_rhd_axi_0_0_ooc.xdc rfile:../../../../../rhd.gen/sources_1/bd/rhd_axi_tb/ip/rhd_axi_tb_rhd_axi_0_0/rhd_axi_tb_rhd_axi_0_0_ooc.xdc id:5 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Repos/UG3-HeadWornUnit-V2-Firmware/rhd/rhd.runs/rhd_axi_tb_rhd_axi_0_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:6} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 17.857 [get_pins inst/rhd_S00_AXI/rhd/fifo_inst/rd_clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 4 [get_pins inst/rhd_S00_AXI/rhd/fifo_inst/wr_clk]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells inst/rhd_S00_AXI/rhd/fifo_inst]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 2.5 [get_pins inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_1/xpm_cdc_0/dest_clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_1/xpm_cdc_0/src_clk]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_1/xpm_cdc_0]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 2.5 [get_pins inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_2/xpm_cdc_0/dest_clk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_2/xpm_cdc_0/src_clk]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_2/xpm_cdc_0]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 2.5 [get_pins inst/rhd_S00_AXI/rhd/xpm_cdc_5bit_inst_3/xpm_cdc_0/dest_clk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins inst/rhd_S00_AXI/rhd/xpm_cdc_5bit_inst_3/xpm_cdc_0/src_clk]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells inst/rhd_S00_AXI/rhd/xpm_cdc_5bit_inst_3/xpm_cdc_0]
set_property src_info {type:SCOPED_XDC file:5 line:55 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 10.000 -name M_AXIS_ACLK [get_ports M_AXIS_ACLK]
set_property src_info {type:SCOPED_XDC file:5 line:57 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 10.000 -name s00_axi_aclk [get_ports s00_axi_aclk]
set_property src_info {type:XDC file:6 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/rhd_S00_AXI/rhd/fifo_inst]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/rhd_S00_AXI/rhd/xpm_cdc_5bit_inst_3]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_1/xpm_cdc_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/rhd_S00_AXI/rhd/xpm_cdc_1bit_inst_2/xpm_cdc_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst/rhd_S00_AXI/rhd/xpm_cdc_5bit_inst_3/xpm_cdc_0]
