# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/anhha/Desktop/UG3_HeadWornUnitV2_FPGA/rhd/rhd.srcs/sources_1/bd/rhd_axi_tb/ip/rhd_axi_tb_axi_vip_0_0/rhd_axi_tb_axi_vip_0_0.xci
# IP: The module: 'rhd_axi_tb_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/anhha/Desktop/UG3_HeadWornUnitV2_FPGA/rhd/rhd.gen/sources_1/bd/rhd_axi_tb/ip/rhd_axi_tb_axi_vip_0_0/rhd_axi_tb_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rhd_axi_tb_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/anhha/Desktop/UG3_HeadWornUnitV2_FPGA/rhd/rhd.srcs/sources_1/bd/rhd_axi_tb/ip/rhd_axi_tb_axi_vip_0_0/rhd_axi_tb_axi_vip_0_0.xci
# IP: The module: 'rhd_axi_tb_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/anhha/Desktop/UG3_HeadWornUnitV2_FPGA/rhd/rhd.gen/sources_1/bd/rhd_axi_tb/ip/rhd_axi_tb_axi_vip_0_0/rhd_axi_tb_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rhd_axi_tb_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
