# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/anhha/Desktop/UG3-HeadWornUnit-V2-Firmware/rhs/rhs.srcs/sources_1/bd/rhs_axi_tb/ip/rhs_axi_tb_axi_vip_0_0/rhs_axi_tb_axi_vip_0_0.xci
# IP: The module: 'rhs_axi_tb_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/anhha/Desktop/UG3-HeadWornUnit-V2-Firmware/rhs/rhs.gen/sources_1/bd/rhs_axi_tb/ip/rhs_axi_tb_axi_vip_0_0/rhs_axi_tb_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rhs_axi_tb_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/anhha/Desktop/UG3-HeadWornUnit-V2-Firmware/rhs/rhs.srcs/sources_1/bd/rhs_axi_tb/ip/rhs_axi_tb_axi_vip_0_0/rhs_axi_tb_axi_vip_0_0.xci
# IP: The module: 'rhs_axi_tb_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/anhha/Desktop/UG3-HeadWornUnit-V2-Firmware/rhs/rhs.gen/sources_1/bd/rhs_axi_tb/ip/rhs_axi_tb_axi_vip_0_0/rhs_axi_tb_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rhs_axi_tb_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
